# Name of this GitHub Actions workflow.
name: Semgrep

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}
  # Scan mainline branches and report all findings:
  push:
    branches: ["master", "main"]
  # Schedule the CI job (this method uses cron syntax):
  schedule:
    - cron: '10 12 * * *'
    # It is recommended to change the schedule to a random time.

jobs:
  call-semgrep:
    uses: sebas-org/reusable-workflow/.github/workflows/semgrep.yml@main
    secrets: inherit